export default {
  login: "victorsonet",
  id: 67899758,
  node_id: "MDQ6VXNlcjY3ODk5NzU4",
  avatar_url: "https://avatars.githubusercontent.com/u/67899758?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/victorsonet",
  html_url: "https://github.com/victorsonet",
  followers_url: "https://api.github.com/users/victorsonet/followers",
  following_url:
    "https://api.github.com/users/victorsonet/following{/other_user}",
  gists_url: "https://api.github.com/users/victorsonet/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/victorsonet/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/victorsonet/subscriptions",
  organizations_url: "https://api.github.com/users/victorsonet/orgs",
  repos_url: "https://api.github.com/users/victorsonet/repos",
  events_url: "https://api.github.com/users/victorsonet/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/victorsonet/received_events",
  type: "User",
  site_admin: false,
  name: "Viktor Kovács",
  company: null,
  blog: "",
  location: "Serbia",
  email: null,
  hireable: null,
  bio: "Frontend Web Developer who previously worked as a Head Coach/Assistant Coach/Analyst in Esports!",
  twitter_username: "victorsoNator",
  public_repos: 44,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2020-07-06T09:20:29Z",
  updated_at: "2024-03-25T14:31:34Z",
};
